### PR TITLE
Test suite

### LINKED ISSUE #60: Error test suite
### Discussed in https://github.com/LouisGariepy/cornucopia/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **Virgiel** May 22, 2022</sup>
It might be interesting to have a test suite that checks that we still catch errors after refactoring. I've started experimenting with this in my [fork](https://github.com/Virgiel/cornucopia/tree/test_suite).

My idea is to write some Toml files describing inputs and the expected error:
```toml
[[test]]
name = "PgParamInExtendedQuery"
query = """
--! new_author
INSERT INTO Author (id, name) VALUES (:id, $1);
"""
error = """
Error while reading queries [path: "queries/module_1.sql"]:  --> 2:45
  | 
  | INSERT INTO Author (id, name) VALUES (:id, $1);
  |                                             ^---
  | 
  = Indexed bind parameters (`$index`) are not allowed when using the extended syntax.
  = Consider using a named bind parameter like `:identifier`, or use the PostgreSQL-compatible syntax..
"""

[[test]]
name = "ColumnNameAlreadyTaken"
migration = """
CREATE TABLE item (
  name TEXT,
  price INTEGER
);
"""
query = """
--! items
SELECT name, price AS name FROM item;
"""
error = """
Error while preparing query "items" [file: "queries/module_1.sql", line: 1]:
Two or more columns have the same name: `name`. Consider disambiguing the column names with `AS` clauses.
"""
```
Then we have a test runner that generates a temporary file tree with the specified queries and migrations, runs cornucopia CLI on it and checks the returned error. By testing at the boundaries, we can change the underlying code without changing the tests and when we change the error message, we should have an option for the test runner to automatically update the error message in the test descriptor.

### PR DESCRIPTION
**Pull request by Virgiel**
The test runner is a separate binary that can be run as a CLI with formatted colored output or as a cargo unit test. Two types of tests are available, error tests that check that errors are caught and return a well-formatted message, and example tests that check that all the examples work. 

Error tests are described in TOML files:
```toml
[[test]]
name = 'ColumnNameAlreadyTaken'
query = '''
--! items
SELECT name, price AS name FROM item;
'''
migration = '''
CREATE TABLE item (
  name TEXT,
  price INTEGER
);
'''
error = '''
Error while preparing query "items" [file: "queries/module_1.sql", line: 1]:
Two or more columns have the same name: `name`. Consider disambiguing the column names with `AS` clauses.'''
```

Closes #60

### CODE REVIEW

**Comment by Virgiel** [comment]
We could also move the codegen tests to the new binary. Having them in the Cornucopia crate is annoying when experimenting.

**Comment by LouisGariepy** [comment]
@Virgiel Thanks for your work on this PR. Now that #52  is out of the way, I'll be able to look into it soon.

Do you think it'd be useful if I implemented #55 sooner rather than later so you can use the lib API?

**Comment by Virgiel** [comment]
> Do you think it'd be useful if I implemented #55 sooner rather than later so you can use the lib API?

Yes, this would allow testing the current codegen change without reinstalling the binary on the system

**Comment by Virgiel** [comment]
We should run the integration tests and examples in the CI

**Comment by LouisGariepy** [comment]
Nice work. 

> We could also move the codegen tests to the new binary. Having them in the Cornucopia crate is annoying when experimenting.

What's your idea for codegen tests? Do you think it'd be sufficient to match the generated code string? Or should we actually generate some usage code and actually do a insert/select assertion, as was done previously?

**Comment by LouisGariepy** [comment]
> We could also move the codegen tests to the new binary. Having them in the Cornucopia crate is annoying when experimenting.

Agreed. Do you reckon we should match the generated code string, or should we

**Comment by Virgiel** [comment]
As long as the generated code compiles, everything should be fine since `postgres` handles all the actual logic. We should still have some usage code to stress the lifetime statements.
We would need to test both async and sync, and have a fairly complex setup to touch every part of the codegen code.

**Comment by LouisGariepy** [comment]
A massive improvement. Sorry it took a bit of time to review. Looks good to me.

**Pull request merged**
