### PR TITLE
Switch rust_decimal to BigDecimal, and increase precision to match Postgres NUMERIC type precision

### PR DESCRIPTION
**Pull request by farazfazli**
Addresses #204, WIP. Currently, facing an error due to BigDecimal not implementing the FromSql<'a> trait.

### CODE REVIEW

**Comment by farazfazli** [comment]
@xoac @LouisGariepy Any ideas on how to fix this? Looks like due to language design, I can't add an additional trait to an external type.

**Comment by LouisGariepy** [comment]
@farazfazli That's right. To implement a trait, you must either own the type or the trait. This is called "orphan rules".

**Comment by farazfazli** [comment]
@LouisGariepy Makes sense, thanks for explaining. I will look into what's needed to open a PR upstream.

**Comment by farazfazli** [comment]
Looks like the BigDecimal crate is hardly maintained, and rust_decimal has a hard limit of 28 digits for precision: https://github.com/paupino/rust-decimal/issues/562

**Comment by farazfazli** [comment]
Closing this PR for now, we can create a new one if a crate is found which satisfies our requirements.

**Pull request closed without merging**
