### PR TITLE
Null everywhere

### LINKED ISSUE #65: Null everywhere
Currently, we can declare the nullity of the returned rows fields:

```sql
CREATE TYPE composite AS (
    name TEXT,
    age INT NOT NULL
);

CREATE TABLE items (
    composite composite,
    name TEXT NOT NULL,
    data BYTEA,
    datas BYTEA[]
);
```

```sql
--! items ?{composite, data, datas}
SELECT * FROM items;
```

This is enough to cover the nullity of `data`, `datas` and `composite` but not the values of `datas` and `composite.name`.

## Nullable array value

We need a way to declare the nullity of the array and the values of the array independently which current syntax does not allow.

We could get back to something close to the old syntax:
- `datas?` means nullable array
- `datas[?]` means nullable array values
- `datas?, datas[?]` or `datas?[?]` means nullable array and array values
```sql
--! items {composite?, data?, datas?[?]}
SELECT * FROM items;
```

# Nullable composite fields

We could declare it in functions declaration:

- `composite?` means nullable composite
- `composite.name?` means nullable composite's name
- `composite?, composite.name?` or `composite?.name?` means nullable composite and composite's name 

```sql
--! items {composite?.name?, data?, datas?}
SELECT * FROM items;
```

But this implies a redeclaration each time we use this composite type. We could add a new syntax to declare the nullity of fields of database types :

```sql
--:db composite{name?}
```

# Nullable parameters

We could use the same syntax for parameters and rows:

```sql
--! new_items (composite?, data?, datas?[?]) {data?}
INSERT INTO items (composite, name, data, datas) 
  VALUES (:composite, :name, :data, :datas) 
  RETURNING name, data;
```

# Nullable named generated types fields

Depends on #63 

We could also use this syntax for named generated type :
```sql
--:params ItemParams{composite?, data?, datas?[?]}
--:row Item{composite?, data?, datas?[?]}

--! new_items (IdParams) -> Item
INSERT INTO items (composite, name, data, datas) 
  VALUES (:composite, :name, :data, :datas) 
  RETURNING *;
```

### PR DESCRIPTION
**Pull request by Virgiel**
Support for internal nullity for array values and database types.

Close #65

### CODE REVIEW

**Comment by Virgiel** [comment]
While working on this PR I removed named type kind from the syntax:
```sql
--: row Named(price?)
--: param NamedParams(price?)
```
become
```sql
--: Named(price?)
--: NamedParams(price?)
```

These kind annotations are not necessary as named types are already prohibited from having the same name. This can add complexity to the validation logic, but it simplify the syntax. We could possibly always add `Params` when generating the params type, which would allow the following:

```sql
--: Named(price?)
```

**Comment by Virgiel** [comment]
The bad news is that I also discovered that my extended test for domain type support was not used and the test is failing :/

**Comment by LouisGariepy** [comment]
> While working on this PR I removed named type kind from the syntax:

+1!

> The bad news is that I also discovered that my extended test for domain type support was not used and the test is failing :/

Oof. Sorry, should've been more careful when I reviewed the PR 😳

**Comment by Virgiel** [comment]
I found a fix and made the test even more extreme. There is only one place where `accepts` returns false but the database accepts `to_sql` output, so I always return to true. I'm not sure that `accepts` has any real use.

**Comment by Virgiel** [comment]
We could simplify a lot by bringing back a generic domain wrapper for params only https://github.com/Virgiel/cornucopia/tree/domain_wrapper.

**Comment by Virgiel** [comment]
Fix all domain related errors and test their support more severely.

**Comment by Virgiel** [comment]
Ready to merge if it suits you

**Comment by LouisGariepy** [comment]
:+1: Its crazy to me how far the project has come since I made it public. Thank you for you contributions!  I especially appreciate the work you put into the test suite. Domains now seem to be escaped and injected in the right places, and we have our intended nullity syntax. Amazing!

**Comment by Virgiel** [comment]
Thank you! I enjoy working on this project with you. I think we are doing something that people will appreciate.
Unless you want the Statement API to be ready for v0.8, we just need to work on errors, documentation and testing 🥳

**Pull request merged**
