### PR TITLE
Use GAT to live our Query API dream

### PR DESCRIPTION
**Pull request by Virgiel**
This is an experimental PR showing how the soon-to-be-stabilised[GAT](https://github.com/rust-lang/rust/pull/96709) feature can help us generate less code.

### CODE REVIEW

**Comment by LouisGariepy** [comment]
I think GATs also stabilize async in traits? A lot of improvements!

**Comment by LouisGariepy** [comment]
There seems to be some uncertainty about the stabilization. I really hope it goes through :sweat_smile: .

**Comment by LouisGariepy** [comment]
:tada: GATs have been merged :) Barring some further issues, I think that means we can expect them on stable in about 3 months or so.

**Comment by Virgiel** [comment]
Unfortunately, this solution has reached a dead end. The orphan rule prevents us from generating the Borrow trait for types from other crates. The truth is that we don't need GAT, it would not improve performance or compile time. If we want to make the generated code smaller or easier to read, we can always use macro_rules to de-duplicate the code generation.

**Pull request closed without merging**
