### PR TITLE
Separate sync async clients

### PR DESCRIPTION
**Pull request by LouisGariepy**
The basic groundwork for separate sync and async clients.

The specifics might be off, I tried to go about this while making the least amount of changes, but there might be a better way to go about this.

### CODE REVIEW

**Comment by Virgiel** [comment]
I'll put cornucopia_client_core in private to make sure I don't publish it: https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field
I would be in favour of renaming the client folders to be more succinct: `sync`, `async` and `core`. Of course, we keep long names for the crates.
Otherwise I validate these changes!

**Review by Virgiel — APPROVED** [review]
I'll put cornucopia_client_core in private to make sure I don't publish it: https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field
I would be in favour of renaming the client folders to be more succinct: `sync`, `async` and `core`. Of course, we keep long names for the crates.
Otherwise I validate these changes!

**Comment by Virgiel** [comment]
We could even use `cornucopia_sync` and `cornucopia_async` for clients name.

**Comment by LouisGariepy** [comment]
Names should be good now!

I also added `publish = false` to `client_core`.

**Pull request merged**
